apiVersion: v1
kind: Service
metadata:
  name: hello-gitops
spec:
  type: NodePort              # <— MUST be here
  selector:
    app: hello-gitops
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080        # <— optional. use between 30000–32767