apiVersion: v1
kind: Service
metadata:
  name: hello-gitops
spec:
  type: NodePort           # this exposes pod outside the cluster
  selector:
    app: hello-gitops
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 