apiVersion: v1
kind: Service
metadata:
  name: backstage-service
  namespace: backstage
spec:
  type: NodePort
  selector:
    app: backstage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7007
      nodePort: 30007